# Generated by Django 4.1 on 2022-09-01 07:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('model', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('coupe', 'Coupe'), ('minivan', 'MiniVan'), ('sports_car', 'Sports Car'), ('hatchback', 'Hatch Back'), ('pickup_truck', 'Pickup Truck')], default='sedan', max_length=50)),
                ('year', models.IntegerField()),
                ('transmission', models.TextField(choices=[('auto', 'Automatic'), ('manual', 'Manual')], default='manual', max_length=50)),
                ('condition', models.TextField(choices=[('used', 'Used'), ('new', 'New')], default='new', max_length=50)),
                ('registration_city', models.CharField(max_length=100)),
                ('hybrid', models.TextField(blank=True, choices=[('full', 'Fully Hybrid'), ('mild', 'Mild Hybrid'), ('plugin', 'Plug-in Hyrbid')], max_length=50, null=True)),
                ('fuel', models.CharField(blank=True, choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('cng', 'CNG'), ('bio_diesel', 'Bio Diesel'), ('lgp', 'LPG')], max_length=50, null=True)),
                ('distance_covered', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(100000)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
