# Generated by Django 4.1 on 2022-08-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carad',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
