# Generated by Django 4.1 on 2022-09-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_listing', '0002_alter_carad_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='carad',
            name='image',
            field=models.ImageField(blank=True, default='avatar.png', null=True, upload_to='../static/images/cars'),
        ),
    ]
