# Generated by Django 4.1 on 2022-08-31 06:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_listing', '0002_alter_carad_distance_covered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carad',
            name='distance_covered',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='carad',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(100000)]),
        ),
    ]
