# Generated by Django 4.1 on 2022-08-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_listing', '0003_alter_carad_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carad',
            name='slug',
            field=models.SlugField(auto_created=True, max_length=200, unique=True),
        ),
    ]
