# Generated by Django 4.1 on 2022-09-01 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_listing', '0004_carad_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carad',
            name='description',
        ),
    ]
