# Generated by Django 4.1 on 2022-08-31 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_listing', '0005_alter_carad_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carad',
            name='distance_covered',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
