# Generated by Django 4.1 on 2022-08-31 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_listing', '0006_alter_carad_distance_covered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carad',
            name='fuel',
            field=models.CharField(blank=True, choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('cng', 'CNG'), ('bio_diesel', 'Bio Diesel'), ('lgp', 'LPG')], max_length=50, null=True),
        ),
    ]
