# Generated by Django 4.1 on 2022-09-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_listing', '0006_carad_color_carad_engine_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carad',
            name='fuel',
            field=models.CharField(blank=True, choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('CNG', 'CNG'), ('Bio Diesel', 'Bio Diesel'), ('LPG', 'LPG')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='carad',
            name='type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Coupe', 'Coupe'), ('Minivan', 'MiniVan'), ('Sports Car', 'Sports Car'), ('Hatch Back', 'Hatch Back'), ('Pickup Truck', 'Pickup Truck')], default='Sedan', max_length=50),
        ),
    ]
