# Generated by Django 4.1 on 2022-09-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_listing', '0008_alter_carad_distance_covered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carad',
            name='fuel',
            field=models.CharField(blank=True, choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('cng', 'CNG'), ('bio_diesel', 'Bio Diesel'), ('lpg', 'LPG')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='carad',
            name='type',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('coupe', 'Coupe'), ('minivan', 'MiniVan'), ('sports_car', 'Sports Car'), ('hatchback', 'Hatch Back'), ('pickup_truck', 'Pickup Truck')], default='sedan', max_length=50),
        ),
    ]
