# Generated by Django 4.1 on 2022-09-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_listing', '0010_alter_carad_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carad',
            name='image',
            field=models.ImageField(blank=True, default='avatar.png', null=True, upload_to='carimages'),
        ),
    ]
