# Generated by Django 4.1 on 2022-09-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_listing', '0011_alter_carad_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='carimages'),
        ),
    ]
