export const GET_ALL_ADS_REQUEST = 'GET_ALL_ADS_REQUEST';
export const GET_ALL_ADS_SUCCESS = 'GET_ALL_ADS_SUCCESS';
export const GET_ALL_ADS_FAIL = 'GET_ALL_ADS_FAIL';

export const GET_AD_REQUEST = 'GET_AD_REQUEST';
export const GET_AD_SUCCESS = 'GET_AD_SUCCESS';
export const GET_AD_FAIL = 'GET_AD_FAIL';

export const GET_MY_ADS_REQUEST = 'GET_MY_ADS_REQUEST';
export const GET_MY_ADS_SUCCESS = 'GET_MY_ADS_SUCCESS';
export const GET_MY_ADS_FAIL = 'GET_MY_ADS_FAIL';

export const POST_AD_REQUEST = 'POST_AD_REQUEST';
export const POST_AD_SUCCESS = 'POST_AD_SUCCESS';
export const POST_AD_FAIL = 'POST_AD_FAIL';

export const UPDATE_AD_REQUEST = 'UPDATE_AD_REQUEST';
export const UPDATE_AD_SUCCESS = 'UPDATE_AD_SUCCESS';
export const UPDATE_AD_FAIL = 'UPDATE_AD_FAIL';
export const UPDATE_AD_RESET = 'UPDATE_AD_RESET';

export const DELETE_AD_REQUEST = 'DELETE_AD_REQUEST';
export const DELETE_AD_SUCCESS = 'DELETE_AD_SUCCESS';
export const DELETE_AD_FAIL = 'DELETE_AD_FAIL';
export const DELETE_AD_RESET = 'DELETE_AD_RESET';
