# Generated by Django 4.1 on 2022-08-31 06:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
